[package]
version = "0.1.0"
name = "script"
edition = "2021"
default-run = "verify"

[[bin]]
name = "verify"
path = "src/bin/main.rs"

[dependencies]
sp1-sdk = { version = "4.1.3", features = ["native-gnark"] }
tracing = "0.1.40"

[build-dependencies]
sp1-build = "4.1.3"
