[package]
version = "0.1.0"
name = "aggregator"
edition = "2021"

[dependencies]
sp1-zkvm = { version = "4.1.3", features = ["verify"] }
sp1-lib = { version = "4.1.3", features = ["verify"] }
sha2 = "0.10.8"
